### ISSUE TITLE
RFE: [mgr] Provide an import based on flat file

### ISSUE THREAD

**Issue by jaymzh** [jaymzh/pius#113]
We already regex mbox parts, we can do the same thing for a flat file. Would be useful for KSPs that don't provide keyrings, just a file (ala FOSDEM).

**Comment by libBletchley** [comment]
FYI there is a FOSDEM keyring:

https://ksp.fosdem.org/files/non-authoritative/keyring.gpg

**Comment by jaymzh** [comment]
I'm aware, but it's unofficial, not signed, and the verification process is inexact. It'd be nice to just generate one from the signed list.

**Comment by libBletchley** [comment]
ah, right.

**Comment by libBletchley** [comment]
I came up with this ugly-ass shit to verify the binary keyring:

`gpg --print-md RIPEMD160 <(cat <(sed -e '/^001/,$d' ksp-fosdem2019.txt) <(./keylist.txt.sh) <(tail -n 2 ksp-fosdem2019.txt))`

The `keylist.txt.sh` comes from https://ksp.fosdem.org/files/non-authoritative/scripts/.
