### ISSUE TITLE
default port incorrectly documented

### ISSUE THREAD

**Issue by libBletchley** [jaymzh/pius#115]
The default port is `587` according to this doc:

https://github.com/jaymzh/pius/

The default port is `25` according to the man page.  One of them must be wrong.  The man page is most likely correct but I've not tested it.

**Comment by jaymzh** [comment]
The man page was changed to reflect 587 back in a19ffec25009a21551e314a7d361a2f7579cd332

**Comment by jaymzh** [comment]
Fixed in 2.2.7.
