### ISSUE TITLE
pius crashes if /tmp folder already exists

### ISSUE THREAD

**Issue by jnsnow** [jaymzh/pius#12]
If pius crashes under a particular user (userA) and later userB attempts to use pius, userB will find that pius crashes in several different spots because of the files left in /tmp by userA.

pius should probably:
- Create temp directories per-pid to avoid races
- Attempt to clean them on abnormal exit, if at all possible.

Observed on 2.1.1-3.fc22.

**Comment by jaymzh** [comment]
Good call. Thanks.

**Comment by jaymzh** [comment]
This was fixed a while back - it will no longer crash.
