### ISSUE TITLE
pius does not declare dependency on "six"

### ISSUE THREAD

**Issue by aabdnn** [jaymzh/pius#130]
I just installed pius 2.2.7 under python 3.7. When I ran "pius -h", I got:

```
pius -h
Traceback (most recent call last):
  File "/Users/anandb/Python/default/bin/pius", line 27, in <module>
    from six.moves import input
ModuleNotFoundError: No module named 'six'
```

It looks like pius requires the python "six" module, but it doesn't declare this as a requirement in its setup.py file.

**Comment by jaymzh** [comment]
yeah the contribution of python3 compatability was woefully lacking. :( the 3_work branch drops py2 support, as well as the `six` requirement...

**Comment by jaymzh** [comment]
Actually, `master` DOES have this dependency:

```
  requires=['six'],
```

This bug must be out of date, closing.
