### ISSUE TITLE
-e option is broken

### ISSUE THREAD

**Issue by yangfl** [jaymzh/pius#138]
I tried
```
./pius -e -A -r ~/.gnupg/pubring.kbx -s 123456
```
Got
```
Traceback (most recent call last):
  File "/home/x/pius/./pius", line 365, in <module>
    main()
  File "/home/x/pius/./pius", line 346, in main
    if signer.sign_all_uids(key, retval):
  File "/home/x/pius/libpius/signer.py", line 741, in sign_all_uids
    self.encrypt_signed_uid(key, uid["file"])
  File "/home/x/pius/libpius/signer.py", line 405, in encrypt_signed_uid
    gpg.stdin.write("\n")
TypeError: a bytes-like object is required, not 'str'
```
Everything goes well without `-e`.

**Comment by jaymzh** [comment]
Ran you run it with `--debug`, and include the output? I need to know what key it choked on to repro.

**Comment by yangfl** [comment]
Have you verified this user/key, and if so, what level do you want to sign at?
  0-3, Show again, Next, Help, or Quit? [0|1|2|3|s|n|h|q] (default: n) 3

Signing all UIDs on key 3E2696CCCDCA8563
DEBUG: Running: /usr/bin/gpg --use-agent --keyid-format long --no-default-keyring --no-auto-check-trustdb -q --no-tty --batch --command-fd 0 --status-fd 1 --keyring x/.gnupg/pubring.kbx --no-options --with-colons --edit-key 3E2696CCCDCA8563
DEBUG: Got a line [GNUPG:] KEY_CONSIDERED 0F6D0B9707F186F0561D3F1A3E2696CCCDCA8563 0
DEBUG: Got a line sec:-:3072:1:3E2696CCCDCA8563:1609748783:1672820783::-:::sc
DEBUG: Got a line fpr:::::::::0F6D0B9707F186F0561D3F1A3E2696CCCDCA8563:
DEBUG: Got a line ssb:-:3072:1:FF8133AE5D084F26:1609748783:1672820783:::::e
DEBUG: Got a line fpr:::::::::FA11E6A273AAF2DB0147DD62FF8133AE5D084F26:
DEBUG: Got a line uid:-::::::::bbbbb <b@b.com>:::S9 S8 S7 S2 H10 H9 H8 H11 H2 Z2 Z3 Z1,mdc,no-ks-modify:1,p::
DEBUG: Got UID bbbbb <b@b.com> with status -
DEBUG: got email b@b.com
DEBUG: 3E2696CCCDCA8563__b_at_b.com__779F7A3084C056E686561E1AF592F5A23B7B1744 isn't in []
DEBUG: got to command prompt
DEBUG: waiting
  There is 1 UID on this key to sign
DEBUG: exporting 779F7A3084C056E686561E1AF592F5A23B7B1744
DEBUG: Running: /usr/bin/gpg --use-agent --keyid-format long --no-default-keyring --no-auto-check-trustdb -q --no-tty --batch --keyring x/.gnupg/pubring.kbx --armor --output /tmp/pius_tmp/779F7A3084C056E686561E1AF592F5A23B7B1744.asc --export 779F7A3084C056E686561E1AF592F5A23B7B1744
DEBUG: exporting 3E2696CCCDCA8563
DEBUG: Running: /usr/bin/gpg --use-agent --keyid-format long --no-default-keyring --no-auto-check-trustdb -q --no-tty --batch --keyring x/.gnupg/pubring.kbx --armor --output /tmp/pius_tmp/3E2696CCCDCA8563.asc --export 3E2696CCCDCA8563
  UID 1 (b@b.com): DEBUG: importing 779F7A3084C056E686561E1AF592F5A23B7B1744
DEBUG: Running: /usr/bin/gpg --use-agent --keyid-format long --no-default-keyring --no-auto-check-trustdb -q --no-tty --batch --keyring /tmp/pius_tmp/pius_keyring.gpg --import-options import-minimal,keep-ownertrust --import /tmp/pius_tmp/779F7A3084C056E686561E1AF592F5A23B7B1744.asc
DEBUG: importing 3E2696CCCDCA8563
DEBUG: Running: /usr/bin/gpg --use-agent --keyid-format long --no-default-keyring --no-auto-check-trustdb -q --no-tty --batch --keyring /tmp/pius_tmp/pius_keyring.gpg --import-options import-minimal --import /tmp/pius_tmp/3E2696CCCDCA8563.asc
DEBUG: Running: /usr/bin/gpg --use-agent --keyid-format long --no-default-keyring --no-auto-check-trustdb -q --no-tty --batch --command-fd 0 --status-fd 1 --keyring /tmp/pius_tmp/pius_keyring.gpg -u 779F7A3084C056E686561E1AF592F5A23B7B1744 --default-cert-level 3 --no-ask-cert-level --edit-key 3E2696CCCDCA8563
DEBUG: Waiting for prompt
DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: got line [GNUPG:] KEY_CONSIDERED 0F6D0B9707F186F0561D3F1A3E2696CCCDCA8563 0
DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: got line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: Selecting UID 1
DEBUG: Waiting for ack
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Running sign subcommand
DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: got line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: Sending sign command
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Waiting for response
DEBUG: Got [GNUPG:] KEY_CONSIDERED 779F7A3084C056E686561E1AF592F5A23B7B1744 0

DEBUG: Got KEY_CONSIDERED
DEBUG: Waiting for response
DEBUG: Got [GNUPG:] GET_BOOL sign_uid.okay

DEBUG: Confirming signing
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Got [GNUPG:] GET_LINE keyedit.prompt

DEBUG: Saving key
signedDEBUG: exporting 3E2696CCCDCA8563
DEBUG: Running: /usr/bin/gpg --use-agent --keyid-format long --no-default-keyring --no-auto-check-trustdb -q --no-tty --batch --keyring /tmp/pius_tmp/pius_keyring.gpg --armor --output /tmp/pius_out/3E2696CCCDCA8563__b_at_b.com__779F7A3084C056E686561E1AF592F5A23B7B1744.asc --export 3E2696CCCDCA8563
DEBUG: Running: /usr/bin/gpg --use-agent --keyid-format long --no-default-keyring --no-auto-check-trustdb -q --no-tty --batch --command-fd 0 --status-fd 1 --keyring /tmp/pius_tmp/pius_keyring.gpg --always-trust --armor -r 3E2696CCCDCA8563 --output /tmp/pius_out/3E2696CCCDCA8563__b_at_b.com__779F7A3084C056E686561E1AF592F5A23B7B1744_ENCRYPTED.asc -e /tmp/pius_out/3E2696CCCDCA8563__b_at_b.com__779F7A3084C056E686561E1AF592F5A23B7B1744.asc
Traceback (most recent call last):
  File "x/pius/./pius", line 365, in <module>
    main()
  File "x/pius/./pius", line 346, in main
    if signer.sign_all_uids(key, retval):
  File "x/pius/libpius/signer.py", line 741, in sign_all_uids
    self.encrypt_signed_uid(key, uid["file"])
  File "x/pius/libpius/signer.py", line 405, in encrypt_signed_uid
    gpg.stdin.write("\n")
TypeError: a bytes-like object is required, not 'str'

**Comment by yangfl** [comment]
And if I get it right
https://github.com/jaymzh/pius/blob/19b61c3b0dc31ee60341b3ca708f8e459e44ce3f/libpius/signer.py#L254-L268
`subprocess.Popen` now wants `bytes` as its streams, however fixing `gpg.stdin.write("\n")` with `gpg.stdin.write(b"\n")` other errors will then come up.

**Comment by jaymzh** [comment]
Thanks. See the attached PR which fixes it.
