### ISSUE TITLE
Incorrect RPM specification file

### ISSUE THREAD

**Issue by zpuskas** [jaymzh/pius#18]
RPM specification file seems to be incorrect as it has missing/incorrect file specs:
* pius-report
* libpius
* README instad of README.md
* README.keyring-mgr instead of README-keyring-mgr

That being said, I did not try to build an RPM package (don't own such a system). I found this by browsing around the source package as I ran into the issue of missing libpius while making a Gentoo ebuild for v2.2.1.

**Comment by jaymzh** [comment]
Good call, thanks for the report. Will get that fixed before next release. I also don't use RPM-based systems these days which is how I missed it. :)
