### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jaymzh** [jaymzh/pius#2]
[ Migrated from: https://sourceforge.net/p/pgpius/feature-requests/6/ ]

The script is currently written in python 2. Some users would like it to run under python 3.

**Comment by wget** [comment]
Great idea. Some GNU/Linux distributions [like Fedora](https://fedoraproject.org/wiki/Changes/Python_3_as_Default) begin to use Python 3 as default to the extend python 2.7 isn't easily installable.
If we convert your script to Python 3, do we need to keep compatibility with 2.7? I'm against personally and am quite radical with legacy management.

**Comment by jaymzh** [comment]
I'm not a fan of python3. It's very cumbersome and since we deal mostly with string parsing which 3 makes more difficult, this is pretty low priority for me. It'll probably happen eventually, but python2 will be in distros for a long time yet.

**Comment by jaymzh** [comment]
Closed by #26

**Comment by jaymzh** [comment]
The python 3 support added never really worked properly. Re-opening this to track full migration as part of PIUS3

**Comment by jaymzh** [comment]
https://github.com/jaymzh/pius/commit/137f672bd8a30d52053388df57c6d4b6a20b8017 on the `3_work` branch seems to work for me for a few base cases (for `pius`, other binaries not yet tested)

**Comment by jaymzh** [comment]
For anyone watching this, I believe the `3_work` branch is now fully python3.

I'm not yet taking advantage of some py3 features I'd like to (typing, format strings), but I don't want to until after the initial PIUS 3.x release.

If those of you who are excited about py3 support could give the `3_work` branch a shit and report any errors here, that'd be helpful.

**Comment by lechner** [comment]
I packaged the `3_work` branch for Debian (but did no testing besides running `pius` successfully without arguments).

**Comment by jaymzh** [comment]
3.0.0 is now out which fixes this.
