### ISSUE TITLE
Error on passphrase prompt

### ISSUE THREAD

**Issue by gtswagger** [jaymzh/pius#30]
Howdy Phil.  I'm trying to sign the SCaLE 14x keyring and running into problems.

=== Command:
python2.7 ./pius -d -r ~/scale-14x-keyring.gpg -s (mykeyid) -A -a -m (myemail) -I

=== Error:  
DEBUG: Confirming signing
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Got [GNUPG:] USERID_HINT (REDACTED ... info on my GPG key here)
DEBUG: Got [GNUPG:] ERROR get_passphrase (REDACTED ... some numbers, not sure if they're relevant to my key as well)

  ERROR: Agent reported an error.

gpg-agent problems, bailing out!

=== Version Stuff:
Pius 2.2.2 Release

$ gpg --help | head -n 14
gpg (GnuPG) 2.0.28
libgcrypt 1.6.3
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA, RSA, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

$ emerge --info | head -n 8
Portage 2.2.20.1 (python 3.4.1-final-0, default/linux/amd64/13.0/desktop/kde, gcc-4.9.3, glibc-2.21-r1, 4.1.12-gentoo x86_64)
 =================================================================
System uname: Linux-4.1.12-gentoo-x86_64-Intel-R-_Core-TM-_i7-5820K_CPU_@_3.30GHz-with-gentoo-2.2
KiB Mem:    16369812 total,    106740 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Wed, 17 Feb 2016 19:00:01 +0000
sh bash 4.3_p39
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1

**Comment by jaymzh** [comment]
Do you have an agent running? can it pop up a prompt if you use gpg directly?

**Comment by gtswagger** [comment]
Ah.  Spotify tried to crash my system earlier by taking all its resources.   That seemed to have locked up gpg-agent.  Seemed to go through after kicking it in the pants.  Cheers.
