### ISSUE TITLE
Hang when trying to apply signature policy

### ISSUE THREAD

**Issue by dephraser** [jaymzh/pius#33]
Trying to sign many keys after a key signing party.
Pius version is 2.2.2. This has been observed in both GnuPG 1.4.18 and GnuPG 2.0.26 (running in TAILS).

Add a policy URL to the options at invocation. Call looks like:
./pius -s 8602A07 -A -r keyring.gpg -U https:://ksp.dephraser.net/ksp_20160426.html -m derp@derp.com -N -d

I have attached the main body of the output. It appears GPG doesn't respond as expected and pius gets caught in an infinite while waiting for gpg to respond.

Still trying to work this one out myself but putting this here if people with a bit more experience automating GPG stuff might know something I don't.

Any questions let me know.

Cheers

[out.txt](https://github.com/jaymzh/pius/files/239425/out.txt)

**Comment by philpennock** [comment]
Confirmed with pius 2.2.2 and GnuPG 2.1.5

**Comment by philpennock** [comment]
```
572     cmd = [self.gpg] + self.gpg_base_opts + self.gpg_quiet_opts + \
573       self.gpg_fd_opts + keyring + [
574           '-u', self.force_signer,
575       ] + agent + [
576           '--default-cert-level', level,
577           '--no-ask-cert-level',
578           '--edit-key', key,
579       ] + self.policy_opts()
```

The edit-key needs to come at the end, options before the key-id.

So two issues:

1. mis-ordered command-line construction
2. stdout closed from gpg command invocation not handled, goes into infinite loop instead of erroring.
