### ISSUE TITLE
pius fails when trying to confirm signing

### ISSUE THREAD

**Issue by jaymzh** [jaymzh/pius#4]
[ Migrated from: https://sourceforge.net/p/pgpius/bugs/18/ ]

$ gpg --version
gpg (GnuPG) 2.1.2
libgcrypt 1.6.3

$ pius --version
pius 2.1.0

$ pius -s 1A3AB57F 4592C73F -d
Welcome to PIUS, the PGP Individual UID Signer.

Setting debug
[...]
DEBUG: got line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: Sending sign command
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Waiting for response
DEBUG: Got [GNUPG:] GET_BOOL sign_uid.okay

DEBUG: Confirming signing
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Got [GNUPG:] GET_LINE keyedit.prompt

  ERROR: GPG didn't sign.
Traceback (most recent call last):
  File "/usr/bin/pius", line 394, in <module>
    main()
  File "/usr/bin/pius", line 378, in main
    if signer.sign_all_uids(key, retval):
  File "/usr/lib/python2.7/site-packages/libpius/signer.py", line 675, in sign_all_uids
    res = self.sign_uid(key, uid['index'], level)
  File "/usr/lib/python2.7/site-packages/libpius/signer.py", line 628, in sign_uid
    raise GpgUnknownError(line)
libpius.exceptions.GpgUnknownError: [GNUPG:] GET_LINE keyedit.prompt

full debug output here: http://ix.io/gRx

**Comment by jeroentbt** [comment]
There is a patch available for pius in the aur that fixes this issue for me.
https://aur.archlinux.org/packages/pius/

**Comment by jaymzh** [comment]
I'm so glad they pushed that patch upstream. *sigh*

Anyway, tracking proper gpg2 support in #10  - I've pushed a branch that should work to gpg2support, please try.

**Comment by zorun** [comment]
> I'm so glad they pushed that patch upstream. sigh

Well, I'm the maintainer of the AUR package, and if you remember correctly, I sent you some patches by email ;)
(I guess that was before the move to github)

**Comment by jaymzh** [comment]
hmm missed that. Anyway, we have full gpg2 support in a released version now. :)

**Comment by jeroentbt** [comment]
Sunshine, lollipops and rainbows everywhere.
Thank you both! :)
