### ISSUE TITLE
Asking for confirmation for each user ID

### ISSUE THREAD

**Issue by civodul** [jaymzh/pius#40]
The attached patch allows users to confirm each user ID explicitly before they are signed and emailed.

[confirm-each-uid-patch.txt](https://github.com/jaymzh/pius/files/428748/confirm-each-uid-patch.txt)

This is useful when a key has several user ID, but the user does not have any information about some of the user IDs.

**Comment by jaymzh** [comment]
Please send a pull request. Thanks!
