### ISSUE TITLE
pius gets public keyring safety-check wrong

### ISSUE THREAD

**Issue by philpennock** [jaymzh/pius#41]
Using GnuPG 2.1, the public keys are in `~/.gnupg/pubring.kbx` but on start-up `pius` checks for the existence of `~/.gnupg/pubring.gpg` instead.

**Comment by philpennock** [comment]
Using `pius -r pubring.kbx` reveals that the help text that bare filenames are assumed relative to to `~/.gnupg/` is false.  Using `pius -r ~/.gnupg/pubring.kbx` does work and lets `pius` progress to doing useful work.

**Comment by philpennock** [comment]
(Tests with pius 2.2.0 release)

**Comment by jaymzh** [comment]
Can you provide a command-line you used and what the error was?

GnuPG often assumes keyrings are in ~/.gnupg/ I had this happen just today when it created some new keyring in there even though the keyring file I gave was in the current directory. It might act different on different platforms however.

**Comment by philpennock** [comment]
I've not used pius in a while, but the above report assumes a new enough version of GnuPG that the KBX format is being used for key storage, instead of a flat-file of PGP binary packets one after another.  It would reproduce with any current version of GnuPG, which currently means 2.2.5.  AFAIK this sort of behavior changes across GnuPG versions but not across platforms.

**Comment by jaymzh** [comment]
Oh. I see what you're saying.

Yes, we check it exists in the CWD, always. But we *warn* that GPG may interpret this poorly. The help is unclear, I will update it.

**Comment by philpennock** [comment]
That addresses the issue with why I originally had issues with the workaround for the bug but not the bug itself.

Newer GnuPG does not use `pubring.gpg` any more.  It uses `pubring.kbx`.  We can work around it, but it's still a glitch.

**Comment by jaymzh** [comment]
Oh you want the default for `-r` changed? It shouldn't default to **either** quite frankly. PIUS is not designed to be run on your public keyring, it's designed to be run on a *party* keyring. The fact that it happens to default to pubring.gpg is just because I couldn't come up with anything else. If I change it, it'll be `/tmp/pubring.pbx` or something.
