### ISSUE TITLE
please do a new release

### ISSUE THREAD

**Issue by pwnage101** [jaymzh/pius#46]
The commit merged in #44 resolves a fatal issue with my basic use case:

```
$ pius --keyring=~/.gnupg/pubring.kbx --use-agent -s <my-keyid> <another-person>
...
Signing all UIDs on key <another-person>
  There are 3 UIDs on this key to sign
  UID 1 (<uid-1>):   ERROR: GnuPG reported an unknown error
  UID 2 (<uid-2>):   ERROR: GnuPG reported an unknown error
  UID 3 (<uid-3>):   ERROR: GnuPG reported an unknown error
```

The specific problem is that `KEY_CONSIDERED` is not handled in the latest release (2.2.2).

I use gpg and gpg-agent 2.1 because that is what Guix currently packages.  If I switched to gpg 2.0, I would not have this problem but would run into another problem: gpg <2.1 cannot read keybox (.kbx) files, the new standard for pubring and trustdb that gpg 2.1 automatically migrates to.  My only reasonable option (which did not involve hacking my keyring files) was to clone this repository.

Can somebody do a new release so we can package a working version for Guix?

**Comment by pwnage101** [comment]
I would like to clarify that this does generally affect any operating system which distributes gpg 2.1 alongside pius, assuming my use case is a valid and common one.

**Comment by jaymzh** [comment]
I'll try to get a new release out soon...

**Comment by pwnage101** [comment]
FYI: The pius package in Guix has been updated from 2.2.2 to 2.2.2-0.891687c [0].  It takes pius git commit 891687ccb3d232a1fc0e7da7d22572c0318644cb instead of downloading a release tarball, and makes gnupg-2.1 a dependency instead of gnupg-2.0.

[0] https://lists.gnu.org/archive/html/guix-devel/2016-12/msg01155.html

**Comment by jaymzh** [comment]
2.2.3 is out the door!
