### ISSUE TITLE
Default mail server is 'None' instead of 'localhost'

### ISSUE THREAD

**Issue by rockdaboot** [jaymzh/pius#57]
Pius 2.2.4 on Debian unstable.

The man page says:
```
       -H HOSTNAME, --mail-host=HOSTNAME
              Hostname of SMTP server. [default: localhost]
```

Without using -H I get
```
...
There was a problem talking to the mail server (None): please run connect() first
``

Adding `-H localhost` fixes it.

**Comment by jaymzh** [comment]
I can't repro this - do you have a ~/.pius/puisrc that's setting `mail_host=` maybe?

What's the full command you are running?

**Comment by rockdaboot** [comment]
There is no  `~/.pius/puisrc`, just installed pius without doing any configuration.

Command example `pius -m <my_email> -s <my long key> <short key>

**Comment by rockdaboot** [comment]
`/usr/bin/pius` doesn't use DEFAULT_MAIL_HOST anywhere. I installed the pius package from Debian. Maybe it is outdated ?

**Comment by lechner** [comment]
The man page is incorrect. `pius -h` shows that the default for `-H` is **none**.

The man page came from the Debian maintainer. It will be fixed in the next upload. Thank you!

**Comment by rockdaboot** [comment]
Good. What about having reasonable defaults like 'localhost' for the server ? Not doing so should error when missing the -H option, right ? At least in most cases.

**Comment by jaymzh** [comment]
Oh, I see what's going on and why I couldn't repro this. I'll get a fix out.

I need to finish the work I did to properly finish factoring out the options code.

**Comment by jaymzh** [comment]
@lechner - don't fix the man page, with this PR it'll be correct. :)
