### ISSUE TITLE
pius crashes on GET_LINE keyedit.prompt

### ISSUE THREAD

**Issue by wget** [jaymzh/pius#6]
Trying to sign my 117 FOSDEM keys, I was experiencing a weird bug with Pius, even with the latest code from the Git master branch. Pius seems to crash when pgp answers by `GET_LINE`. I could bypass the check at [line 629](https://github.com/jaymzh/pius/blob/master/libpius/signer.py#L629), but I don't know what would be the consequences.

> Welcome to PIUS, the PGP Individual UID Signer.
> 
> NOTE: See the README about security implications.
> Please enter your PGP passphrase: 
> Please enter your mail server password: 
> pub   rsa4096/25BF484F08AB4849 2013-02-18 [expires: 2016-04-01]
>       Key fingerprint = 569D E362 A219 F26B 2C0F  3B7A 25BF 484F 08AB 4849
> uid               [ unknown] Niels Laukens
> uid               [ unknown] Niels Laukens <niels@dest-unreach.be>
> uid               [ unknown] Niels Laukens (FOSDEM) <niels@fosdem.org>
> sub   rsa4096/4FE0DE7E265FB534 2014-12-13 [expires: 2016-04-01]
> sub   rsa4096/D810E3BDB2F490BC 2014-12-13 [expires: 2016-04-01]
> 
> Have you verified this user/key, and if so, what level do you want to sign at?
>   0-3, Show again, Next, Help, or Quit? [0|1|2|3|s|n|h|q] (default: n) 3
> 
> Signing all UIDs on key 25BF484F08AB4849
>   There are 3 UIDs on this key to sign
>   UID 1 (Niels_Laukens):   ERROR: GPG didn't sign.
> Traceback (most recent call last):
>   File "./pius", line 395, in <module>
>     main()
>   File "./pius", line 379, in main
>     if signer.sign_all_uids(key, retval):
>   File "/home/wget/IT/Dev/pius/libpius/signer.py", line 676, in sign_all_uids
>     res = self.sign_uid(key, uid['index'], level)
>   File "/home/wget/IT/Dev/pius/libpius/signer.py", line 629, in sign_uid
>     raise GpgUnknownError(line)
> libpius.exceptions.GpgUnknownError: [GNUPG:] GET_LINE keyedit.prompt

With debug mode enabled:

> (master)[wget@hermes pius]$ python2.7 ./pius -d --mail-host=xxx.com --mail=foo@bar.com --signer=0E7DE52C04D71683 $(echo $list) --mail-user=foo@bar.com --keyring=~/.gnupg/pubring.kbx --override-email=foo@bar.com
> Welcome to PIUS, the PGP Individual UID Signer.
> 
> Setting debug
> NOTE: See the README about security implications.
> Please enter your PGP passphrase: 
> DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--no-armor', '--always-trust', '-r', '0E7DE52C04D71683', '-e', '/tmp/pius_tmp/pius_tmp']
> DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--command-fd', '0', '--passphrase-fd', '0', '--status-fd', '1', '--output', '/tmp/pius_tmp/pius_tmp2', '-d', '/tmp/pius_tmp/pius_tmp.gpg']
> DEBUG: Sending passphrase
> DEBUG: wait()ing on gpg
> Please enter your mail server password: 
> DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--no-default-keyring', '--keyring', '/home/wget/.gnupg/pubring.kbx', '--fingerprint', '25BF484F08AB4849']
> pub   rsa4096/25BF484F08AB4849 2013-02-18 [expires: 2016-04-01]
>       Key fingerprint = 569D E362 A219 F26B 2C0F  3B7A 25BF 484F 08AB 4849
> uid               [ unknown] Niels Laukens
> uid               [ unknown] Niels Laukens <niels@dest-unreach.be>
> uid               [ unknown] Niels Laukens (FOSDEM) <niels@fosdem.org>
> sub   rsa4096/4FE0DE7E265FB534 2014-12-13 [expires: 2016-04-01]
> sub   rsa4096/D810E3BDB2F490BC 2014-12-13 [expires: 2016-04-01]
> 
> Have you verified this user/key, and if so, what level do you want to sign at?
>   0-3, Show again, Next, Help, or Quit? [0|1|2|3|s|n|h|q] (default: n) 3 
> 
> Signing all UIDs on key 25BF484F08AB4849
> DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--command-fd', '0', '--passphrase-fd', '0', '--status-fd', '1', '--no-default-keyring', '--keyring', '/home/wget/.gnupg/pubring.kbx', '--no-options', '--with-colons', '--edit-key', '25BF484F08AB4849']
> DEBUG: Got a line [GNUPG:] KEYEXPIRED 1396353588
> DEBUG: Got a line [GNUPG:] KEYEXPIRED 1427882391
> DEBUG: Got a line pub:-:4096:1:25BF484F08AB4849:1361218378:1459526401::-:::sc
> DEBUG: Got a line fpr:::::::::569DE362A219F26B2C0F3B7A25BF484F08AB4849:
> DEBUG: Got a line sub:e:4096:1:50D362AFBC565821:1361223395:1396353582:::::e
> DEBUG: Got a line fpr:::::::::7354A5A725A96B65E2DD660750D362AFBC565821:
> DEBUG: Got a line sub:e:4096:1:DDF18CE10D7AC10C:1361223585:1396353588:::::s
> DEBUG: Got a line fpr:::::::::A94E9B41E8943BDCC48694D9DDF18CE10D7AC10C:
> DEBUG: Got a line sub:e:4096:1:A7829D04C69C578D:1387451398:1427882391:::::s
> DEBUG: Got a line fpr:::::::::2EFFEDBB5C3466A41B6D1D2CA7829D04C69C578D:
> DEBUG: Got a line sub:e:4096:1:13F552BB4E87B2C5:1387451764:1427882389:::::e
> DEBUG: Got a line fpr:::::::::AB2BA0D826E40484128329DA13F552BB4E87B2C5:
> DEBUG: Got a line sub:[GNUPG:] KEYEXPIRED 1396353588
> DEBUG: Got a line [GNUPG:] KEYEXPIRED 1427882391
> DEBUG: Got a line -:4096:1:4FE0DE7E265FB534:1418477951:1459526328:::::s
> DEBUG: Got a line fpr:::::::::217A91942C1A3713485E5A7F4FE0DE7E265FB534:
> DEBUG: Got a line sub:-:4096:1:D810E3BDB2F490BC:1418478602:1459526387:::::e
> DEBUG: Got a line fpr:::::::::4D75342A53830731CCEF5390D810E3BDB2F490BC:
> DEBUG: Got a line uid:-::::::::Niels Laukens:::S9 S8 S7 S3 H10 H9 H8 H11 Z2 Z3 Z1 Z0,mdc,no-ks-modify:1,p:
> DEBUG: Got UID Niels Laukens with status -
> DEBUG: no email
> DEBUG: 25BF484F08AB4849__Niels_Laukens__0E7DE52C04D71683 isn't in []
> DEBUG: Got a line uid:-::::::::Niels Laukens <niels@dest-unreach.be>:::S9 S8 S7 S3 H10 H9 H8 H11 Z2 Z3 Z1 Z0,mdc,no-ks-modify:2,:
> DEBUG: Got UID Niels Laukens <niels@dest-unreach.be> with status -
> DEBUG: got email niels@dest-unreach.be
> DEBUG: 25BF484F08AB4849__niels_at_dest-unreach.be__0E7DE52C04D71683 isn't in ['25BF484F08AB4849__Niels_Laukens__0E7DE52C04D71683']
> DEBUG: Got a line uid:-::::::::Niels Laukens (FOSDEM) <niels@fosdem.org>:::S9 S8 S7 S3 H10 H9 H8 H11 Z2 Z3 Z1 Z0,mdc,no-ks-modify:3,:
> DEBUG: Got UID Niels Laukens (FOSDEM) <niels@fosdem.org> with status -
> DEBUG: got email niels@fosdem.org
> DEBUG: 25BF484F08AB4849__niels_at_fosdem.org__0E7DE52C04D71683 isn't in ['25BF484F08AB4849__Niels_Laukens__0E7DE52C04D71683', '25BF484F08AB4849__niels_at_dest-unreach.be__0E7DE52C04D71683']
> DEBUG: got to command prompt
> DEBUG: quitting
> DEBUG: waiting
>   There are 3 UIDs on this key to sign
> DEBUG: exporting 25BF484F08AB4849
> DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--no-default-keyring', '--keyring', '/home/wget/.gnupg/pubring.kbx', '--armor', '--output', '/tmp/pius_tmp/25BF484F08AB4849.asc', '--export', '25BF484F08AB4849', '0E7DE52C04D71683']
>   UID 1 (Niels_Laukens): DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--no-default-keyring', '--keyring', '/tmp/pius_tmp/pius_keyring.gpg', '--import-options', 'import-minimal', '--import', '/tmp/pius_tmp/25BF484F08AB4849.asc']
> DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--command-fd', '0', '--passphrase-fd', '0', '--status-fd', '1', '--no-default-keyring', '--keyring', '/tmp/pius_tmp/pius_keyring.gpg', '-u', '0E7DE52C04D71683', '--default-cert-level', '3', '--no-ask-cert-level', '--edit-key', '25BF484F08AB4849']
> DEBUG: Sending passphrase
> DEBUG: Waiting for prompt
> DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
> DEBUG: got line [GNUPG:] KEYEXPIRED 1396353588
> DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
> DEBUG: got line [GNUPG:] KEYEXPIRED 1427882391
> DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
> DEBUG: got line [GNUPG:] GET_LINE keyedit.prompt
> DEBUG: Selecting UID 1
> DEBUG: Waiting for ack
> DEBUG: Waiting for line [GNUPG:] GOT_IT
> DEBUG: got line [GNUPG:] GOT_IT
> DEBUG: Running sign subcommand
> DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
> DEBUG: got line [GNUPG:] GET_LINE keyedit.prompt
> DEBUG: Sending sign command
> DEBUG: Waiting for line [GNUPG:] GOT_IT
> DEBUG: got line [GNUPG:] GOT_IT
> DEBUG: Waiting for response
> DEBUG: Got [GNUPG:] GET_BOOL sign_uid.okay
> 
> DEBUG: Confirming signing
> DEBUG: Waiting for line [GNUPG:] GOT_IT
> DEBUG: got line [GNUPG:] GOT_IT
> DEBUG: Got [GNUPG:] GET_LINE keyedit.prompt
> 
>   ERROR: GPG didn't sign.
> Traceback (most recent call last):
>   File "./pius", line 395, in <module>
>     main()
>   File "./pius", line 379, in main
>     if signer.sign_all_uids(key, retval):
>   File "/home/wget/IT/Dev/pius/libpius/signer.py", line 676, in sign_all_uids
>     res = self.sign_uid(key, uid['index'], level)
>   File "/home/wget/IT/Dev/pius/libpius/signer.py", line 629, in sign_uid
>     raise GpgUnknownError(line)
> libpius.exceptions.GpgUnknownError: [GNUPG:] GET_LINE keyedit.prompt
>

**Comment by jaymzh** [comment]
Thanks for the bug report. Can you give me your version of PGP? Usually this is from someone on PGP 2.x, which I haven't figured out support for yet, it still requires 1.x.

**Comment by wget** [comment]
> gpg (GnuPG) 2.1.4
> libgcrypt 1.6.3
> Copyright (C) 2015 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Home: ~/.gnupg
> Supported algorithms:
> Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
> Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
>         CAMELLIA128, CAMELLIA192, CAMELLIA256
> Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
> Compression: Uncompressed, ZIP, ZLIB, BZIP2

What's weird is that some of my friends running on ArchLinux (like me) signed their FOSDEM keys using pius and haven't experienced problems with it.

**Comment by wget** [comment]
I thought your script was compatible with gpg 2.x, you mentioned that version in the README.
Don't get me wrong, but I think we should drop legacy and thus gpg 1.x, and Python 2.7 (I saw you enhancing request to move to python 3).
Also, could you precise in the README, the requirements (gpg and python versions), in that way people interested in using pius don't lose their time figuring why this is not working.

**Comment by miquelruiz** [comment]
I made it work in gpg 2.1.4 with this changes:
https://github.com/miquelruiz/pius/commit/cf7b6f4fab905844fc322010a8e297ed72df5f5a

**Comment by jnsnow** [comment]
I am seeing this behavior with gpg 1.14.19-2.fc22 ... I have both gpg1 and gpg2 installed, but /usr/bin/gpg which is the default is the 1.14 version and I am seeing the GET_LINE quit during the confirmation phase.

**Comment by jaymzh** [comment]
@jnsnow Can you file a separate bug with  'gpg --version' and debug output of the crash? This case was a gpg2 specific problem, and once I release a version that checks for gpg1 in the next week or so I'm going to close this bug (and keep the gpg2-support bug open). Thanks!

**Comment by jnsnow** [comment]
User error, actually, sorry. There was another problem where the key was not getting signed, it's just that pius was not reporting or showing me what that error was, because of the --no-tty option. So pius was properly dying, it was just hard to debug.

Which made it /look/ like this bug, but it was something else.

**Comment by jaymzh** [comment]
Thanks for following up. :)

**Comment by jaymzh** [comment]
#10  is the tracking bug for gpg2, so I'm going to close this.

I've pushed experimental gpg2 support to the gpg2support branch, please test.
