### ISSUE TITLE
Fails at creating keyring

### ISSUE THREAD

**Issue by lhirlimann** [jaymzh/pius#60]
[ludo@Oulanl pius]$ ls -l \$HOME/sfoksp2017.gpg 
ls: cannot access '$HOME/sfoksp2017.gpg': No such file or directory
[ludo@Oulanl pius]$ pius-keyring-mgr build -r /home/ludovic/sfoksp2017.gpg -b /home/ludo/.thunderbird/cs7eroe0.default/Mail/Local\ Folders/kspsfo2017 -m ludovic@mozilla.com -p "Ksp October 2017 SFO/Mozilla"
Found 35 keys in mbox: 34 fingerprints and 1 full keys
NOT Found B3862B05DBAFEC0F
NOT Found 956347F6FBF3A415
NOT Found 51E71B754A09B187
NOT Found B574896780AF07D3
NOT Found 2222222222222222
NOT Found CC8BAD2DF14BA71F
NOT Found EBCA4777BC7A8032
NOT Found A3ADB67A2CDB8B35
NOT Found 709700cdc86c5f3f
NOT Found 5667263747164796
NOT Found d61627b6564796e6
NOT Found 765637f2c6f676f6
NOT Found 76C4315D71A9FECC
NOT Found 4231A03EEC286D08
NOT Found FF77C2E936AEFFF3
NOT Found 262667D75A93A3DE
NOT Found AACCAC21430AF5E7
NOT Found AC8DD49B5C88FF9D
Sending mail to ['wang@yuxuan.org', 'ludovic@mozilla.com']
Traceback (most recent call last):
  File "/usr/bin/pius-keyring-mgr", line 632, in <module>
    main()
  File "/usr/bin/pius-keyring-mgr", line 629, in main
    options.mail_text)
  File "/usr/bin/pius-keyring-mgr", line 358, in send_emails
    self._send_email(override_email, k)
  File "/usr/bin/pius-keyring-mgr", line 278, in _send_email
    smtp = smtplib.SMTP('localhost', '587')
  File "/usr/lib64/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by jaymzh** [comment]
This doesn't look like it's failing to create the keyring, but it's crashing because you gave it an invalid mailserver to talk to. The default is `localhost` on the `submission` port (`587`)  which you have nothing listening on, therefore, when it tried to connect to it to send mail to folks, it crashed. You either need to provide valid mail server options (`--mail-host`, `--mail-port`, and possibly `--mail-user`) or you need to not pass in `-m`.
