### ISSUE TITLE
gpg can't parse some newer keys and thus party-worksheet should use gpg2

### ISSUE THREAD

**Issue by lhirlimann** [jaymzh/pius#62]
[ludo@Oulanl pius]$ ./pius-party-worksheet  /home/ludo/sfoksp2017.gpg >kspsfo.html
gpg: assuming bad signature from key DBAFEC0F due to an unknown critical bit
Use of uninitialized value $owner in substitution (s///) at ./pius-party-worksheet line 114.
Use of uninitialized value $owner in substitution (s///) at ./pius-party-worksheet line 115.
Use of uninitialized value $owner in substitution (s///) at ./pius-party-worksheet line 116.
Use of uninitialized value $owner in hash element at ./pius-party-worksheet line 118.
Use of uninitialized value in concatenation (.) or string at ./pius-party-worksheet line 139.

**Comment by jaymzh** [comment]
Fixed by #63
