### ISSUE TITLE
NameError: global name 'parser' is not defined

### ISSUE THREAD

**Issue by foice** [jaymzh/pius#69]
I installed pius from brew on Mac OS, I am currently stuck with this undefined 'parser' error.
Any idea what is that and how to solve it?

```
Welcome to PIUS, the PGP Individual UID Signer.

Traceback (most recent call last):
  File "/usr/local/bin/pius", line 342, in <module>
    main()
  File "/usr/local/bin/pius", line 275, in main
    options.mail_host
  File "/usr/local/Cellar/pius/2.2.4_1/libexec/lib/python2.7/site-packages/libpius/signer.py", line 91, in __init__
    parser.error('You chose interactive mode but do not have the pexpect'
NameError: global name 'parser' is not defined
```

**Comment by jaymzh** [comment]
You're using this with `interactive` mode which is going away soon. I can have a look, but modern GPG requires an agent anyway, so that mode is no longer usable with gpg 2.1.

**Comment by jaymzh** [comment]
I actually I don't have an old enough version of gpg anywhere to even start to debug this. Sorry. I'm going to close this as invalid, as PIUS 3.x will drop interactive mode altogether since it's not usable anymore.
