### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by felixonmars** [jaymzh/pius#98]
Looks like the git master runs fine in Python 3 while the latest tag doesn't. Is a new release planned soon? Thanks!

**Comment by jaymzh** [comment]
I'm hoping to wrap up the 3-x release branch soon, but if I don't I'll do another 2.x release.

**Comment by cdluminate** [comment]
+1 from Debian user.

**Comment by lechner** [comment]
@felixonmars Which commits are needed to make `pius` work with Python 3 again, please? I would like to cherry-pick them into the Debian package, which is presently broken. Thank you!

**Comment by felixonmars** [comment]
I didn't really bisect into it, just made sure the master works and submitted this issue. On Arch Linux I chose to just package pius for Python 2 and wait for a new release before moving to Python 3.

**Comment by lechner** [comment]
@felixonmars I did the same thing for Debian. Thank you!

**Comment by jaymzh** [comment]
Sorry, life's been crazy I haven't forgotten this. But yes, I keep master working - so it's generally safe to use that. :)

**Comment by jaymzh** [comment]
2.2.7 is out.
